name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_reqs:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ "macOS-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.8"]
    env:
      UPLOAD_ARTIFACT: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate new requirements_frozen_${{ matrix.os }}.txt if needed
        if: ${{ github.event_name == 'push' }}  # Only runs when branch pushed to directly OR when a PR is merged
        shell: bash
        run: |
          pip freeze > requirements_frozen_temp.txt
          if diff requirements_frozen_${{ matrix.os }}.txt requirements_frozen_temp.txt > /dev/null; then
            echo "requirements_frozen_${{ matrix.os }}.txt unchanged"
            rm requirements_frozen_temp.txt
          else 
            echo "requirements_frozen_${{ matrix.os }}.txt is different, git push needed"
            mv requirements_frozen_temp.txt requirements_frozen_${{ matrix.os }}.txt
            echo "UPLOAD_ARTIFACT=true" >> "$GITHUB_ENV"
          fi

      - name: Store artifact
        if: env.UPLOAD_ARTIFACT == 'true'  # Only runs when requirements_frozen is updated
        uses: actions/upload-artifact@v3
        with:
          name: requirements_frozen_${{ matrix.os }}
          path: requirements_frozen_${{ matrix.os }}.txt
          retention-days: 1

  git_push:
    name: git push changes to requirements
    needs: build_reqs
    runs-on: ubuntu-latest
    env:
      GIT_PUSH_NEEDED: false
      MACOS: requirements_frozen_macOS-latest
      UBUNTU: requirements_frozen_ubuntu-latest
      WINDOWS: requirements_frozen_windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Download requirement artifacts
        uses: actions/download-artifact@v3  # downloads all artifacts
        with:
          path: .

      - name: Check if requirement artifacts exist
        run: |
          if test -f "$MACOS/$MACOS.txt"; then
            mv --force "$MACOS/$MACOS.txt" .
            echo "GIT_PUSH_NEEDED=true" >> "$GITHUB_ENV"
          fi
          if test -f "$UBUNTU/$UBUNTU.txt"; then
            mv --force "$UBUNTU/$UBUNTU.txt" .
            echo "GIT_PUSH_NEEDED=true" >> "$GITHUB_ENV"
          fi
          if test -f "$WINDOWS/$WINDOWS.txt"; then
            mv --force "$WINDOWS/$WINDOWS.txt" .
            echo "GIT_PUSH_NEEDED=true" >> "$GITHUB_ENV"
          fi

      - name: Setup git/add/commit/push for requirements_frozen if needed
        if: env.GIT_PUSH_NEEDED == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "$MACOS.txt" "$UBUNTU.txt" "$WINDOWS.txt"
          git commit -m "GitHub Actions generated updated requirements_frozen"
          git push